###
Get http://localhost:4500/clients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvZWpAZ21haWwuY29tIiwiaWQiOiI2ZmM4MzUyNC0yZTk0LTQ2ZmQtYjE2Zi1kNmI4MzljM2Q5ODYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzkyMjIxNTYsImV4cCI6MTY3OTMwODU1Nn0.wib-9OcFz5ojnS4P-ZqukJzWSAOBQq6px8XcjFCgud4


### 
GET  http://localhost:4500/clients/85a364e6-2cc9-4f8c-baca-03c22cc1e333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvZWpAZ21haWwuY29tIiwiaWQiOiI2ZmM4MzUyNC0yZTk0LTQ2ZmQtYjE2Zi1kNmI4MzljM2Q5ODYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzkyMjIxNTYsImV4cCI6MTY3OTMwODU1Nn0.wib-9OcFz5ojnS4P-ZqukJzWSAOBQq6px8XcjFCgud4

###
Post http://localhost:4500/clients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvZWpAZ21haWwuY29tIiwiaWQiOiI2ZmM4MzUyNC0yZTk0LTQ2ZmQtYjE2Zi1kNmI4MzljM2Q5ODYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzkyMjIxNTYsImV4cCI6MTY3OTMwODU1Nn0.wib-9OcFz5ojnS4P-ZqukJzWSAOBQq6px8XcjFCgud4

{ 
   
    "email":"unga6@gmail.com",   
    "name": "unga",
    "location":"Africa"

}

###
PUT http://localhost:4500/clients/124
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvZWpAZ21haWwuY29tIiwiaWQiOiI2ZmM4MzUyNC0yZTk0LTQ2ZmQtYjE2Zi1kNmI4MzljM2Q5ODYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzkyMjIxNTYsImV4cCI6MTY3OTMwODU1Nn0.wib-9OcFz5ojnS4P-ZqukJzWSAOBQq6px8XcjFCgud4

{ 
 
    "email":"unga@gmail.com",   
    "name": "unga",
    "location":"Africa"

}
###
DELETE  http://localhost:4500/clients/7c244719-3ea4-4f17-87d2-25588be13ff0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvZWpAZ21haWwuY29tIiwiaWQiOiI2ZmM4MzUyNC0yZTk0LTQ2ZmQtYjE2Zi1kNmI4MzljM2Q5ODYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzkyMjIxNTYsImV4cCI6MTY3OTMwODU1Nn0.wib-9OcFz5ojnS4P-ZqukJzWSAOBQq6px8XcjFCgud4

###
Get http://localhost:4500/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvZWpAZ21haWwuY29tIiwiaWQiOiI2ZmM4MzUyNC0yZTk0LTQ2ZmQtYjE2Zi1kNmI4MzljM2Q5ODYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzkyMjIxNTYsImV4cCI6MTY3OTMwODU1Nn0.wib-9OcFz5ojnS4P-ZqukJzWSAOBQq6px8XcjFCgud4

###
Get http://localhost:4500/projects/oo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvZWpAZ21haWwuY29tIiwiaWQiOiI2ZmM4MzUyNC0yZTk0LTQ2ZmQtYjE2Zi1kNmI4MzljM2Q5ODYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzkyMjIxNTYsImV4cCI6MTY3OTMwODU1Nn0.wib-9OcFz5ojnS4P-ZqukJzWSAOBQq6px8XcjFCgud4

###
Post http://localhost:4500/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvZWpAZ21haWwuY29tIiwiaWQiOiI2ZmM4MzUyNC0yZTk0LTQ2ZmQtYjE2Zi1kNmI4MzljM2Q5ODYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzkyMjIxNTYsImV4cCI6MTY3OTMwODU1Nn0.wib-9OcFz5ojnS4P-ZqukJzWSAOBQq6px8XcjFCgud4


{
    "clientId": "bc6745e2-c9f1-4e62-ba5d-cea01c375c22",
    "projectTitle":"Android application",
    "projectType":"Android",
    "assigned_on":"12/02/2023",
    "due_on":"12/01/2023"

}
###
Post http://localhost:4500/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvZWpAZ21haWwuY29tIiwiaWQiOiI2ZmM4MzUyNC0yZTk0LTQ2ZmQtYjE2Zi1kNmI4MzljM2Q5ODYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzkyMjIxNTYsImV4cCI6MTY3OTMwODU1Nn0.wib-9OcFz5ojnS4P-ZqukJzWSAOBQq6px8XcjFCgud4

{
    "clientId": "bc6745e2-c9f1-4e62-ba5d-cea01c375c22",
    "projectTitle":"Android application",
    "projectType":"Android",
    "assigned_on":"12/02/2023",
    "due_on":"12/01/2023"

}

###
Put http://localhost:4500/projects/id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvZWpAZ21haWwuY29tIiwiaWQiOiI2ZmM4MzUyNC0yZTk0LTQ2ZmQtYjE2Zi1kNmI4MzljM2Q5ODYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzkyMjIxNTYsImV4cCI6MTY3OTMwODU1Nn0.wib-9OcFz5ojnS4P-ZqukJzWSAOBQq6px8XcjFCgud4

{
    "clientId": "bc6745e2-c9f1-4e62-ba5d-cea01c375c22",
    "projectTittle":"Android application",
    "projectType":"Android",
    "assigned_on":"12/02/2023",
    "due_on":"12/01/2023"

}

###
Delete http://localhost:4500/projects/:id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvZWpAZ21haWwuY29tIiwiaWQiOiI2ZmM4MzUyNC0yZTk0LTQ2ZmQtYjE2Zi1kNmI4MzljM2Q5ODYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzkyMjIxNTYsImV4cCI6MTY3OTMwODU1Nn0.wib-9OcFz5ojnS4P-ZqukJzWSAOBQq6px8XcjFCgud4

