Post http://localhost:4500/clients/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvZWpAZ21haWwuY29tIiwiaWQiOiI2ZmM4MzUyNC0yZTk0LTQ2ZmQtYjE2Zi1kNmI4MzljM2Q5ODYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2Nzg5ODgxODQsImV4cCI6MTY3OTA3NDU4NH0.JQqTJVi_Sl2UoZheGCLZUEfyVstaW2E7uFSzfSzdw8s

{ 
 
    "email":"john@gmail.com",   
    "name": "Cod.ltd",
    "location":"ju"

}
###
PUT http://localhost:4500/clients/124
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvZWpAZ21haWwuY29tIiwiaWQiOiI2ZmM4MzUyNC0yZTk0LTQ2ZmQtYjE2Zi1kNmI4MzljM2Q5ODYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2Nzg5ODgxODQsImV4cCI6MTY3OTA3NDU4NH0.JQqTJVi_Sl2UoZheGCLZUEfyVstaW2E7uFSzfSzdw8s

{ 
 
    "email":"john@gmail.com",   
    "name": "Cod.ltd",
    "location":"Africa"

}
###
DELETE  http://localhost:4500/clients/7c244719-3ea4-4f17-87d2-25588be13ff0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvZWpAZ21haWwuY29tIiwiaWQiOiI2ZmM4MzUyNC0yZTk0LTQ2ZmQtYjE2Zi1kNmI4MzljM2Q5ODYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2Nzg5ODgxODQsImV4cCI6MTY3OTA3NDU4NH0.JQqTJVi_Sl2UoZheGCLZUEfyVstaW2E7uFSzfSzdw8s

