Post http://localhost:4500/clients/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI4ZjRjYTBkLWM3ZWMtNDFiNy04OTRiLTcxZjhmYTNlM2FkYyIsImlzQWRtaW4iOiJqb2huQGdtYWlsLmNvbSIsImlhdCI6MTY3ODk3Mjc5MSwiZXhwIjoxNjc5MDU5MTkxfQ.6wRSLBOvLXqRsGEO-7N0WoLZ9WK1GCR6tlNArz-6WNQ

{ 
 
    "email":"john@gmail.com",   
    "name": "Cod.ltd",
    "location":"ju"

}
